import type { Metadata } from "next";
import "./globals.css";
import AppChrome from "@/components/AppChrome";
import { initializePermissions } from "@/lib/permissions";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Initialize permissions from database on first page load
  try {
    await initializePermissions();
  } catch (error) {
    console.error("Failed to initialize permissions:", error);
  }

  return (
    <html lang="en">
      <body className="antialiased">
        <AppChrome>{children}</AppChrome>
      </body>
    </html>
  );
}